version: "3.10"
name: project
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      # - ./config/php:/usr/local/etc/
    ports:
      - 9000:80
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7
    hostname: mysql_db.local
    restart: always
    environment:
      MYSQL_DATABASE: "accadify"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "lopslops"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db

volumes:
  my-db:
